KNOWN_COMPANY_ALIASES: dict[str, tuple[str, ...]] = {
    "3M": ("3m", "mmm"),
    "AES Corporation": ("aes corporation", "aes"),
    "AMCOR": ("amcor",),
    "Adobe": ("adobe", "adbe"),
    "Apple": ("apple", "aapl"),
    "Amazon": ("amazon", "amzn"),
    "Alphabet": ("alphabet", "google", "goog", "googl"),
    "Boeing": ("boeing",),
    "Chevron": ("chevron", "cvx"),
    "Coca-Cola": ("coca-cola", "coca cola"),
    "Costco": ("costco",),
    "Exxon Mobil": ("exxon", "exxon mobil", "exxonmobil"),
    "Ford": ("ford", "ford motor"),
    "General Motors": ("general motors", "gm"),
    "Home Depot": ("home depot",),
    "IBM": ("ibm", "international business machines"),
    "Johnson & Johnson": ("johnson & johnson", "johnson and johnson", "jnj"),
    "JPMorgan": ("jpmorgan", "jp morgan", "jpmorgan chase"),
    "Microsoft": ("microsoft", "msft"),
    "NVIDIA": ("nvidia", "nvda"),
    "Oracle": ("oracle",),
    "Pfizer": ("pfizer",),
    "Salesforce": ("salesforce",),
    "Target": ("target",),
    "Tesla": ("tesla", "tsla"),
    "Verizon": ("verizon",),
    "Walmart": ("walmart", "wal-mart"),
}
